
const store = new Vuex.Store({
    state:{
        list:[
            {
                img:"images/1.jpg",
                name:"尊敬的母亲",
                talk:"还想吃啥",
                time:"晚上7:21",
                index:0,
                message:"想吃啥",
                msg:"猪蹄",
                imgs:"images/女.png",
                nicheng:"Liu",
                weixinnum:"123456788",
                area:"吉林 吉林"

            },
            {
                img:"images/2.jpg",
                name:"芳芳",
                talk:"走去吃火锅",
                time:"晚上7:21",
                index:1,
                message:"想吃啥",
                msg:"火锅",
                imgs:"images/女.png",
                nicheng:"潘潘",
                weixinnum:"123456788",
                area:"瑞典 斯德哥尔摩"
            },
            {
                img:"images/3.jpg",
                name:"孙大懒",
                talk:"哈哈哈哈哈哈哈哈哈哈哈",
                time:"晚上7:21",
                index:2,
                message:"哈哈哈哈哈哈哈哈哈哈哈",
                msg:"哈哈哈哈哈哈哈哈哈哈哈",
                imgs:"images/女.png",
                nicheng:"ohh",
                weixinnum:"123456788",
                area:"辽宁 沈阳"
            },
            {
                img:"images/4.jpg",
                name:"大神，偶像",
                talk:"哈哈哈哈哈哈哈哈哈哈哈",
                time:"晚上7:21",
                index:3,
                message:"你不想好了啊",
                msg:"哈哈哈哈哈哈哈哈哈哈哈",
                imgs:"images/男.png",
                nicheng:"KWAHI AM",
                weixinnum:"123456788",
                area:"北京 西城"
            },
            {
                img:"images/5.jpg",
                name:"万伟",
                talk:"哈哈哈哈哈哈哈哈哈哈哈",
                time:"晚上7:21",
                index:4,
                message:"东北有啥好的",
                msg:"哈哈哈哈哈哈哈哈哈哈哈",
                imgs:"images/男.png",
                nicheng:"小目标赚一个亿",
                weixinnum:"123456788",
                area:"江苏 苏州"
            },
            {
                img:"images/6.jpg",
                name:"华娣",
                talk:"好滴",
                time:"晚上7:21",
                index:5,
                message:"到家了没",
                msg:"我到家啦",
                imgs:"images/女.png",
                nicheng:"AKA-LH",
                weixinnum:"123456788",
                area:"江苏 苏州"
            },
            {
                img:"images/7.jpg",
                name:"阿峰",
                talk:"杰哥真棒",
                time:"晚上7:21",
                index:6,
                message:"杰哥加油",
                msg:"好的",
                imgs:"images/男.png",
                nicheng:"SmF",
                weixinnum:"123456788",
                area:"江苏 无锡"
            },
            {
                img:"images/8.jpg",
                name:"麦当劳",
                talk:"不见不散",
                time:"晚上7:21",
                index:7,
                message:"相约麦当劳",
                msg:"好的",
                imgs:"images/男.png",
                nicheng:"麦当劳",
                weixinnum:"123456788",
                area:"全国各地"
            },
            {
                img:"images/9.jpg",
                name:"信用社",
                talk:"晚上来存钱",
                time:"晚上7:21",
                index:8,
                message:"定期存款，让你变成世界首富",
                msg:"好的",
                imgs:"images/男.png",
                nicheng:"card",
                weixinnum:"123456788",
                area:"全国各地"
            },
            {
                img:"images/10.jpg",
                name:"城市pizza",
                talk:"晚上来吃城市pizza",
                time:"晚上7:21",
                index:9,
                message:"别饿到自己",
                msg:"好的",
                imgs:"images/女.png",
                nicheng:"pizza",
                weixinnum:"123456788",
                area:"全国各地"
            },
            {
                img:"images/11.jpg",
                name:"父亲大人",
                talk:"有时间再聊",
                time:"晚上7:21",
                index:10,
                message:"缺钱找你妈",
                msg:"好的",
                imgs:"images/男.png",
                nicheng:"Zhu",
                weixinnum:"123456788",
                area:"吉林 长春"
            }
        ]
    },
  
})
export default store